container_image   = docker://nick2420/pointflow:linux-amd64

initialdir = /home/nachtmann
executable      = run.sh


output         = job_$(Cluster)_$(Process).out
error          = job_$(Cluster)_$(Process).err
log            = job_$(Cluster).log

request_cpus    = 6
request_memory  = 10GB
request_disk    = 8GB

transfer_input_files   = osdf:///chtc/staging/nachtmann/data.tar.gz?pack=auto, train_NF.py
when_to_transfer_output = ON_EXIT
transfer_output_files   = output


queue 1
